### ISSUE TITLE
Context Menu for Widgets

### ISSUE THREAD

**Issue by hhslepicka** [slaclab/pydm#104]
Registering a conversation and idea with @mattgibbs...
The idea is to implement a dropdown Menu for actions that can be performed on the Widget PV(s) such as Plot vs Time, Archive, Show Info, etc...

Idea:
Right Click on widget...
```
PV1 > 
PV2 > 
PV3 >
```

Highlight PV1:
```
PV1 >
   Plot vs Time >
   Archive >
   Info >
   ....
PV2 > 
PV3 >
```

Note: If there is only one PV at the Widget skip the first level and render the actions available.

**Comment by scalverson** [comment]
I really like this idea and think something along these lines is definitely useful, though you may have to think about how this is affected by child widgets which may have there own right-click action implemented.  The info option (I assume this would be like Probe?) especially is useful for the software developers.

Also, as much as I hate to say this, you should probably do this somewhat like how EDM did where the right-click actions are defined in a flat file somewhere so that labs which use different archiver appliances or plotting tools can have it use those instead.  Unless of course you were planning on building those tools into PyDM itself somehow.  Plot vs. time and info would be pretty easy to implement as a pop-up app and could use templates built on already existing widgets.  Archiver might be a bit trickier to be generic and user friendly.

**Comment by mattgibbs** [comment]
Actions are user-definable, but we are going to go with something slightly more complex than a flat file.  Each action is going to be a subclass of some 'PyDMAction' (name not official) class.  There will be a few methods you need to implement,  but beyond that, how it works is up to the author.  This seems like a pretty powerful system - actions could potentially open up a process, remember the pid, and send that process messages (so, you could add more traces to an already-open plotting tool, for example).

This is sort of in the 'PyDM spirit' of being extensible via python classes (Data plugins, widgets, and hopefully actions soon).

As for nested widgets, Qt propagates click events down the widget tree.  Each widget along the tree can react to the event, and decide whether to accept() it, or continue propagating it downward.  So it is up to the widget author, which is probably the right thing to do.  Sometimes you want the click to reach a child widget (like in PyDMEmbeddedDisplay), sometimes you don't (like in PyDMSlider, where we are going to have a PyDMLabel inside it, but don't want to expose that label to clicks).
