### ISSUE TITLE
Accessing channel timestamp and other fields

### ISSUE THREAD

**Issue by peroame** [slaclab/pydm#1107]
I was pointed to this documentation page when I asked about accessing the timestamp of a PV:

https://slaclab.github.io/pydm/widgets/PyDMWidget.html#pydmtooltip-instructions

I have a couple of concerns with this:

1. I would have expected, possibly naively, to be able to access record fields via a pydm channel rather than a widget. Not only it would feel more natural, but, after all, one could have channels without widgets, no?
2. The documentation talks about how to set up tooltip to access these fields but I claim it would be more critical to be able to access these fields programmatically and I could not find how to do that in the documentation. I was told I can use the syntax <widget>.timestamp and I verified it works, but how about the other fields? And why is naming different (eg. .TIME for tooltip vs .timestamp for the programmatic access)? 

Thank you,
Amedeo

**Comment by jbellister-slac** [comment]
> I would have expected, possibly naively, to be able to access record fields via a pydm channel rather than a widget. Not only it would feel more natural, but, after all, one could have channels without widgets, no?

Correct, a channel can  be set up to monitor specific record fields in the same way as camonitor or pvmonitor for example. So `ca://MY:PV.SEVR` and `pva://MY:PV.SEVR` will both be valid ways to create a channel monitoring the alarm severity of an EPICS PV. You'll still need the correct read or write access for the field you are trying to access, TIME I believe is noaccess by default.

>  I was told I can use the syntax .timestamp and I verified it works, but how about the other fields? And why is naming different (eg. .TIME for tooltip vs .timestamp for the programmatic access)?

The properties shared between widgets are in `base.py`, see here for some examples:

https://github.com/slaclab/pydm/blob/8b2742907fa9736663c09e890732d3ccb489c208/pydm/widgets/base.py#L626-L635

The naming for tooltips I believe was matching the convention of other display managers.

If you are writing your own custom widget or code, you can also make your own callbacks rather than monitoring the fields of the widget. When creating a channel, you have access to the following slot parameters that you can use to specify what to run when the field changes:

https://slaclab.github.io/pydm/channel.html

For the built-in widgets, these callbacks are defined in base as well:

https://slaclab.github.io/pydm/widgets/PyDMWidget.html

With each widget overriding methods as needed for extra functionality in their own source code file.
