### ISSUE TITLE
Automatically close idle screens

### ISSUE THREAD

**Issue by mike-zelazny** [slaclab/pydm#150]
Zelazny: Can I get a non-default option to close idle screens after a given number of minutes (like the SCP has)?  That way I don't have 100 non-important screens open forever buried where I'll never see or want them again?

By "idle" I mean so-many minutes have passed since the last button push.

**Comment by hhslepicka** [comment]
@mike-zelazny thank you for opening the issue.
Just to clarify, each one of the screens would have a specific timeout value, right? Or would you like one for the whole application?
How is this currently implemented on EDM?

**Comment by mike-zelazny** [comment]
It is not currently implemented in edm.  It is implemented in the SCP.  The SCP has one global timeout.  Going forward it may or may not be useful to have an idle timeout for each screen.  My initial reaction would be to have one per screen.
________________________________________

**Comment by ZLLentz** [comment]
This is also something the photon side uses in our camviewer for the same reason. It's implemented over here as a sub-window that opens after an hour of sitting idle with a 1-hour countdown. You then have the option to extend the life of the display by clicking on a button rather than having it close unceremoniously.

This would be a very welcome feature in pydm, either on a per-window basis or for the whole application.
