### ISSUE TITLE
PyDMShellCommand - Parameters property

### ISSUE THREAD

**Issue by hhslepicka** [slaclab/pydm#162]
Opening this issue for discussion:
As of now there is no easy way to send in additional parameters to the command to be executed without changing the command property.

The idea is to add a new and optional pyqtproperty to hold a dictionary named parameters which if informed would be appended to the command property.

Example:
One wants to call the following command:
`my_exec --kwargs=foo`

The current implementation requires that you change the command to that or to any other set of parameters desired.

With the parameters property one could do:
```python
command = 'my_exec'
parameters = {"--kwargs":"foo"}
```

This parameters property could be changed on other events without the need to keep changing the command.

What are your inputs into this idea @mattgibbs @gabrielfedel @laispc @fernandohds564 
This need came with a question from @teddyrendahl

**Comment by mattgibbs** [comment]
How would you handle non-paired arguments?  A key with an empty string for the parameter?
```
command = 'cp'
parameters = {"-r": "", "file1": "", "file2": ""}
```
...feels a little strange.  A plain-old list fits shell command syntax a little more naturally, I think.

I'm fine with the idea, but I am sort of skeptical that it is really a big problem to just change the command.

**Comment by hhslepicka** [comment]
Maybe with None as the value for non-paired arguments?
The idea of the list looks good to me, I suggested the dictionary because you can update the values keeping the keys, no strong opinion about that.
In general this issue came as a way to keep the `command` intact and separated from the parameters... not something that is really required but on the list of maybe it is useful for someone.

**Comment by teddyrendahl** [comment]
Yeah. Kind of @mattgibbs though, not convinced changing the command is that much of a hassle.

**Comment by hhslepicka** [comment]
Fair enough! 👍 If anyone find it useful please reopen the issue! Closing as it does not seem to be necessary!

**Comment by laispc** [comment]
Hi, @hhslepicka . I personally do not use the shell widget much often, but I think the idea of adding a property for args is not bad. However, putting args in a dict or list does not seem to be the best option. Args will be more organized but I agree that accessing them would not be so natural. How about a string property in this case?
Anyway, changing this feature does not seem to be urgent. For now, I am okay with defining the whole command. :)

**Comment by fernandohds564** [comment]
Hi @hhslepicka !
Just like @laispc, I do not use this widget very often, in fact I have never used it.
At some extent I agree with what @mattgibbs and @teddyrendahl said, maybe in the QtDesigner it would not make much a difference, but I think this property could be very helpful if we think about specialization classes, where the same command should be used with different arguments along the code, or when different commands that have the same arguments (we have some cases like this) should be called.
The down side is that for a not so obvious gain, the interface of the widget could get less straightforward for the users...
I also think that dictionaries are not the best choice for this property because they don't maintain the order of the arguments, which could be an issue for some commands. Maybe a `list` or an `OrderedDict` are better choices.

Thanks! I hope these points help you in the decision!
