### ISSUE TITLE
Cannot use designer widgets from installed PyDM

### ISSUE THREAD

**Issue by ZLLentz** [slaclab/pydm#234]
`designer_plugin.py` is in the top level, outside of the module, so it isn't included when `pydm` is installed. This means that if I do `conda install pydm` there is no top-level `pydm` directory with `designer_plugin.py` inside it, so there is nowhere to point `PYQTDESIGNERPATH`.

Presumably, we need to either move or copy `designer_plugin.py` one level down into the module itself so it can be distributed with `pydm`. I'm not sure which of the two is preferred, since copying is messier but moving breaks backwards compatibility.

As an aside, it would be really nice if activating a conda environment that has `pydm` installed would set the `PYQTDESIGNERPATH` variable automatically, but that's not super important.

**Comment by hhslepicka** [comment]
Hi Zach,

The idea is that the designer_plugin.py is just an example that should be
done by who install PyDM. We can for sure add it to the package to make it
simpler but it was intended to be left out. In any case users will need to
create the environment variable in order to point to the proper location.
The idea is that different people can point to different widgets or even
limit the widgets that users have access to.

We should revisit the documentation or even maybe the implementation to
cover the points that you mentioned.

Thanks for this one!

**Comment by ZLLentz** [comment]
What advice do you have for those like me who want the following workflow:
- create a central conda install that non-experts can share, but not modify
- `conda install pydm`
- create startup script for others to activate the environment
- user types `designer`, and expects to be able to modify the pydm screens

Do I need to plop a copy of `designer_plugin.py` into a random directory after installing `pydm` if I want to edit a screen? Do I need to have all of my users who want to edit a `pydm` screen check out this repo first, and point `PYQTDESIGNERPATH` to it? The expected workflow for a non-expert to create a screen with `pydm` widgets is unclear.

**Comment by hhslepicka** [comment]
I completely agree with you! It is really unclear at this point but I think
that the best is to change the approach and proceed the way you suggested
with the file at the package. I will do some tests and put a PR soon

**Comment by hhslepicka** [comment]
Solved by #239.
