### ISSUE TITLE
PyDMShellCommand command on Windows needs double \\

### ISSUE THREAD

**Issue by joaopmrod** [slaclab/pydm#305]
For instance this won't work on PyDMShellCommand command:
```
python C:\Users\joaoprod\AppData\Local\Continuum\anaconda3\envs\lsstProtection\Lib\site-packages\pydm_launcher\main.py C:\Users\joaoprod\Documents\GitHub\lsstPLCsTestBox\vaccumMonitor.py
```
```
python: can't open file 'C:UsersjoaoprodAppDataLocalContinuumanaconda3envslsstProtectionLibsite-packagespydm_launchermain.py': [Errno 2] No such file or directory
```

This works on PyDMShellCommand command:
```
python C:\\Users\\joaoprod\\AppData\\Local\\Continuum\\anaconda3\\envs\\lsstProtection\\Lib\\site-packages\\pydm_launcher\\main.py C:\\Users\\joaoprod\\Documents\\GitHub\\lsstPLCsTestBox\\vaccumTests.py
```

I don't know if you want to keep it like this or have it fixed.

**Comment by hhslepicka** [comment]
Thank you @joaopmrod for finding this one...
One solution is for us to write on the documentation educating users to convert the path to `C:/Users/...` instead of `C:\...\...` this will solve the problem... or we can go deeper and try to parse the path if running on windows.
As a first approach we will try the documentation and if this is not effective we move to the code.
I will leave this Issue open until we add the proper documentation in place.
