### ISSUE TITLE
Issues with Decoding Char Waveforms

### ISSUE THREAD

**Issue by ZLLentz** [slaclab/pydm#332]
We had an issue today with waveforms like this not being decoded properly in `widgets.display_format.parse_value_for_display`:
```
array([ 53,  46,  53,  50,  46,  52,  53,  46,  56,  56,  46,  49,  46,
        49,   0, 128, 126, 217,  67, 191, 199,   8, 148,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0], dtype=uint8)
```
In `edm` and in `pyepics` (with `pvobj.get(as_string=True)`) this is truncated at the first zero to display `5.52.45.88.1.1`, but in `pydm` this errors at:
 https://github.com/slaclab/pydm/blob/53741622a5f92e818f59ec3adfefeb52ca2be66d/pydm/widgets/display_format.py#L28
Of course, the problem here is that there are junk characters in our char array, but after some digging it looks like all the other CA clients have this "terminate at first 0" assumption baked in when a char waveform is requested as a string. Instead, pydm fails to decode and this big waveform makes it into the display instead of the IP address. I think the epics modules we're using know about this assumption and make no effort to touch the data after the first 0, but I haven't dug all the way in.

I'm not sure if this is better solved by leaning on `pyepics` or other clients to decode the strings properly, or if this "terminate at 0" assumption should also be baked in to `pydm`.

**Comment by hhslepicka** [comment]
![giphy 3](https://user-images.githubusercontent.com/8185425/40859772-bea4d472-6597-11e8-8548-cdb0c7999b7a.gif)

I honestly think that we can without fear bake this in to `pydm` and only try to convert the content before the first zero if it exists at the exact point where you referenced it.

The display format can be selected per widget so that is why it does not make sense to add it to the data plugin.

Would you mind to put a PR to fix that?
