### ISSUE TITLE
How to install pydm

### ISSUE THREAD

**Issue by mennodoor** [slaclab/pydm#34]
Hello,

could someone explain me how I could install pydm (Windows 7) the way that I can use its widgets in Qt Designer? I tried copying the pydm folder in the qt5-tools/plugins/ and qt5-tools/plugins/designer folder, with no effect... maybe I am completely wrong with this idea, because there is no .dll file provided in pydm... But it says in the readme that its possible to integrate it to Qt Designer...

Thanks for any Tipps...
piuu

**Comment by hhslepicka** [comment]
@piuupiuupiuu, how is your PYQTDESIGNERPATH environment variable configured?
Please see this link for more info on this env var: http://pyqt.sourceforge.net/Docs/PyQt5/designer.html#writing-qt-designer-plugins

**Comment by mattgibbs** [comment]
First: Make sure the PyQt designer plugin is installed.  In Help->About Plugins, you should see the PyQt plugin listed.  If you don't see that, check your Qt/plugins/designer directory to see if the pyqt dll file is there.  If not, you'll need to find where PyQt built the plugin, and copy it into the plugins/designer directory.

Next: Instead of copying the pydm folder into one of the directories listed in PYQTDESIGNERPATH, try adding the path to pydm to the PYQTDESIGNERPATH variable.  For example, if you put pydm at C:\pydm, can set PYQTDESIGNERPATH to

PYQTDESIGNERPATH=C:\pyqt_plugins;C:\Program Files\Python36\Lib\site-packages\PyQt5\Qt\plugins;C:\Program Files\Python36\Lib\site-packages\pyqt5-tools\plugins\designer;C:\pydm

And see if that changes things.

The PyQt plugin for Qt Designer looks in each of the directories in that variable for any python files named *plugin.py.  It won't search subdirectories.  Basically, you need to point Qt Designer to the pydm folder that contains 'designer_plugin.py'.  That file will then import all the PyDM widgets into designer.

Let me know if that fixes it for you!
--Matt

**Comment by piuupiuupiuu** [comment]
Thanks for your Tips!

> Next: Instead of copying the pydm folder into one of the directories listed in PYQTDESIGNERPATH, try adding the path to pydm to the PYQTDESIGNERPATH variable.
This worked! I expected that Qt Designer looks into the subdirectorys -.-

Thanks for your help!
piuu

**Comment by mattgibbs** [comment]
Sounds like this one is solved, I'll close the issue.

**Comment by dschick** [comment]
I just encountered a similar problem with the designer.
pydm is working fine with the provided examples.

I have the pyqt5 plugin installed and it is listed within the designer plugins.
As soon as I add the folder cointaining the `pydm_designer_plugin.py` file to the `PYQTDESIGNERPATH` I get a 
```
Loading PyDM Widgets
Segmentation fault (core dumped)
```
when starting the `designer`.

Is there a way for further debugging this problem?

Many thanks in advance,

Daniel
