### ISSUE TITLE
Macros should be less verbose at command line

### ISSUE THREAD

**Issue by hhslepicka** [slaclab/pydm#350]
Currently users are required to perfectly input the macros as a json string in the following format:
```bash
python pydm.py -m '{"variable": "value"}' my_file.ui
```

The idea is to support a less error prone way.

Some ideas are:

- ```python pydm.py -m variable=value -m variable2=value2 my_file.ui```
- ```python pydm.py -m "P=bclean,CAM=Cam,R="  my_file.ui```

Open to more ideas if any.

Attn. @prjemian

**Comment by teddyrendahl** [comment]
Yes! 👍

**Comment by prjemian** [comment]
This one will be harder to support:

```
python pydm.py -m variable=value -m variable2=value2 my_file.ui
```

Argparse will only deliver the last `-m key=value` set.  Instead, if there are more than one key,value pair, then delimiting the pairs (comma is typical) is successful.  To add white space with the delimiter, wrapping with quotes (single or double) is needed.

A simple addition to the pydm_launcher will come in a PR from my fork.  It goes into the exception branch of this part of the code so that backwards compatibility is maintained:

```
    if pydm_args.macro is not None:
        try:
            macros = json.loads(pydm_args.macro)
        except ValueError:
            raise ValueError("Could not parse macro argument as JSON.")
```

**Comment by prjemian** [comment]
Here's my example command line:

```
python ./main.py -m "AA=aa,BB=bb, CC=c{c}, DD=d[a<b}:_"
```

Argparse sees this string `AA=aa,BB=bb, CC=c{c}, DD=d[a<b}:_`

and the new code creates this dictionary: `{'AA': 'aa', 'BB': 'bb', 'CC': 'c{c}', 'DD': 'd[a<b}:_'}`
