### ISSUE TITLE
PyDMDisplay and PyDMEmbeddedDisplay

### ISSUE THREAD

**Issue by teddyrendahl** [slaclab/pydm#481]
I have to admit I am a little confused at the distinction between these two widgets. They seem to be doing the same thing but each has slightly different features. Both take an external file, give you a widget for that file with the option of passing macros in. 

A few specific points of contention that I see need to be resolved.

* `PyDMDisplay` isn't documented in Sphinx
* ~~`PyDMDisplay` can not load Python files~~
* `PyDMEmbeddedDisplay` requires `PyDMApplication`
* `PyDMEmbeddedDisplay` is not rendered in QtDesigner

**Comment by mattgibbs** [comment]
`Display` (what you are calling `PyDMDisplay` here) is what you are supposed to subclass when you make a Python-based PyDM display.  It happens to be a QWidget subclass, but that is sort of just an implementation detail.

`PyDMEmbeddedDisplay` is one of PyDM's widgets, and is supposed to let you embed a .ui or .py display into another.  You are right - it currently requires PyDMApplication, because that is where nested macros, and keeping track of the current file path happens.  Right now, the display that PyDMEmbeddedDisplay embeds doesn't get rendered in QtDesigner, although that may change in the future...

**Comment by teddyrendahl** [comment]
Thanks for the clarification, I understand the difference now between `Display` and `PyDMEmbeddedDisplay`. I think I've have been doing this in a different way then intended for a while. I still see three of the four items I listed above as actionable items.

**Comment by prjemian** [comment]
time to close this issue?
