### ISSUE TITLE
Allow DataPlugins to force Connect at QtDesigner

### ISSUE THREAD

**Issue by hhslepicka** [slaclab/pydm#639]
**What's the problem this feature will solve?**
Some data plugins are better suited and provide proper experience for users when connecting even when using QtDesigner. E.g.: PCDS Happi plugin which brings information from the underlying python class to compose a screen.
Attn. @klauer 

**Describe the solution you'd like**
- Add an attribute at PyDMPlugin for `designer_online_by_default`
```
class HappiPlugin(PyDMPlugin):
    protocol = 'happi'
    connection_class = HappiConnection
    designer_online_by_default = True
```
- Remove this check from PyDMChannel:
https://github.com/slaclab/pydm/blob/master/pydm/widgets/channel.py#L116-L117
- Delegate the check for whether or not to connect to this method:
https://github.com/slaclab/pydm/blob/daf14f410452b8ef2cccf5ed62dd92bcc46283c8/pydm/data_plugins/plugin.py#L164

**Comment by cristinasewell** [comment]
I want to double check here the Motivation of this Issue, just want to make sure i understand it correctly. 

This is what I think it wants to solve:

By default we want to connect DataPlugins at QT Designer, and it would function as though we have the `PYDM_DESIGNER_ONLINE` environment variable set, but, if any DataPlugins would have this `designer_online_by_default ` set to `False` , there would not be any connections at QtDesigner  - did i get this right?


Would looks something like this in the `add_connection(self, channel)`: 
```
if (is_qt_designer() and not config.DESIGNER_ONLINE and
                not self.designer_online_by_default):
                return
```
otherwise it functions the same way.... 

I think i have a circular dependency here when importing the `is_qt_designer()` so would it be ok to import in the `add_connection` function itself? (`from pydm.utilities import is_qt_designer` ) - i might be wrong here

**Comment by hhslepicka** [comment]
The idea behind the `designer_online_by_default` is to ignore the YES or NO from `DESIGNER_ONLINE` and always be online if running inside of QtDesigner as some plugins such as Happi need to always try to connect to give users the insight on how the screens will look like.

If this variable is set to False (which should be the default), the existing behavior should be used, which is to go with the `config.DESIGNER_ONLINE` approach.

About the circular dependency, if it exists it is fine to import inside of the function as you mentioned. 👍
