### ISSUE TITLE
Lack of Documentation on version v1.11.1

### ISSUE THREAD

**Issue by ZLLentz** [slaclab/pydm#739]
Version v1.11.1 has a very short release notes blurb about the two most recent changes to the library, but actually incorporates a number of other pull requests, some of which added features, and at least one of which (rules enum change) is not backwards compatible- this behavior change required an update to the pmps-ui application used on the photon side of lcls. I think it's worth going back to revise these release notes to be more complete.

Diff comparison for reference: https://github.com/slaclab/pydm/compare/v1.11.0...v1.11.1

**Comment by hhslepicka** [comment]
Oooops... my bad on the `rules enum`.

**Comment by klauer** [comment]
I don't think this was actually addressed. Perhaps you could just use GitHub's built-in support to regenerate the release notes for v1.11.1?

Giving it a try:


# PyDM 1.11.1 Release Notes

Nothing huge, just two small changes we wanted to get out sooner rather than later.

- ENH: Remove the 'Are you sure you want to quit?' dialog box on quit. See #736 
- DOC: Update conda installation instructions.

## What's Changed
* FIX: Make so that ALARM_NONE widgets don't loose their original border. by @hhslepicka in https://github.com/slaclab/pydm/pull/728
* Allow data plugin to force connect at qt designer by @cristinasewell in https://github.com/slaclab/pydm/pull/691
* add polyline drawing widget by @prjemian in https://github.com/slaclab/pydm/pull/580
* Proof-of-concept automatic MEDM ADL converter and loader by @klauer in https://github.com/slaclab/pydm/pull/723
* FIX: Make sure channels with enum use the proper value by @hhslepicka in https://github.com/slaclab/pydm/pull/733
* Make the confirm close dialog optional. by @mattgibbs in https://github.com/slaclab/pydm/pull/736
* Update conda installation instructions. by @mattgibbs in https://github.com/slaclab/pydm/pull/738


**Full Changelog**: https://github.com/slaclab/pydm/compare/v1.11.0...v1.11.1

**Comment by YektaY** [comment]
Ok, I have went ahead a updated the release notes in the same fashion. Thanks for the suggestion!
