### ISSUE TITLE
Remove PYDM from the start of each widget in designer

### ISSUE THREAD

**Issue by TaineEriksen** [slaclab/pydm#743]
Currently all PYDM widget names in designer begin with "PYDM" which makes it harder to scan for the desired widget. Below is a mockup of what I request.

Currently
![Screen Shot 2021-09-17 at 12 10 02 PM](https://user-images.githubusercontent.com/55255100/133841406-e44cd131-b9fc-4374-b139-305b5790955c.png)

Request
![Screen Shot 2021-09-17 at 11 58 21 AM](https://user-images.githubusercontent.com/55255100/133841450-ceaa13ad-fb75-4598-994b-0a5837fa92e6.png)

**Comment by mattgibbs** [comment]
This is smart, we should do this.  My only concern is if there's some name collision between a native Qt widget and the PyDM version of that same widget.  I don't know how designer handles that.  If there's a problem, we might need to use something like "Slider (PyDM)" for the PyDM version.

**Comment by kabanaty** [comment]
If we do implement this, I suggest maintaining PyDM in the widget name somewhere.  I often filter the widget list, and it would be confusing if the list just displays two widgets of the 'same' name.  We'd lose the information that says these widgets do different things.
Ex. 
![PyDMLabel_Filtered](https://user-images.githubusercontent.com/35951619/135162853-dd6ffcc9-5e51-410f-83c6-cadcdf88969c.PNG)
.

**Comment by TaineEriksen** [comment]
I think the easiest solution is to have PYDM appended to the widget name instead of prepended That way we don’t have to worry about name conflicts but get the benefit of being able to skim the list.

**Comment by slactasha** [comment]
I'm going to make the case for leaving it as is, even though it is a bit hard to scan in a hurry (I've personally gotten used to it, or like Tyler I use the filter). 

If the widget name was changed, all the widgets used in files made at SLAC and elsewhere would have to be updated. And since we would have to replace it with something that also included 'pydm' to distinguish it from the standard PyQt widgets there's no real gain. 

If only the widget name/label in Designer was changed, but not the actual widget name, I think this could lead to confusion if there's inconsistency when people switch between graphically building the UI files and coding the interface with Python.

Either way, I would want to make sure there was wide agreement in this before going ahead with any change.

**Comment by YektaY** [comment]
The team has decided to not move forward with this request
