### ISSUE TITLE
Adjust slider step size at run time

### ISSUE THREAD

**Issue by mattgibbs** [slaclab/pydm#826]
The EDM slider widget has a feature where you can right-click it, and a little pop-up will appear that lets you adjust the slider step size, and also just type in a value to go to.  This is pretty useful - it is pretty difficult to set a slider step size that is always the right choice.  If your accelerator's beam energy changes to something much lower, those gentle corrector magnet steps suddenly seem a lot less gentle...

**Comment by slactasha** [comment]
Here are some additional requests for added slider functionality send from Kristi:

I’d like the added functionality to the slider as follows:
Middle (or right) click and window pops up so that you can enter 
a)       value to set
b)      new step size
c)       the step size can be entered or defined as a PV
d)      precision, the default is 1%, but I’d like to have the option to select if precision is entered or defined from a PV prec field 
e)      format of numbers on slider (min,max,current position), float, double,exp
See cater 152517

**Comment by prjemian** [comment]
Related to https://github.com/BCDA-APS/adl2pydm/issues/79
