### ISSUE TITLE
ByteIndicator Does not display negative numbers

### ISSUE THREAD

**Issue by jozamudi** [slaclab/pydm#970]
**Describe the bug**

When the value of the ByteIndicator widget is a negative the byte indicator displays all bits are off.

**Expected behavior**

The byteIndicator should display the bits regardless if the value is signed or unsigned.

**Steps to Reproduce**

Set the value of the ByteIndicator negative.

**Possible Solution**
 

In the ByteIndicator class, the function update_indicators. There is an 'if' statement that sets the value to zero if the value is negative. Removing this 'if' statement fixes the issue.

**My Platform**

**Additional context**

**Comment by YektaY** [comment]
Hello, 

The PyDM is assessing which route to approach this change and were wondering if something like this new widget request #922 work for your needs?

**Comment by C0bit** [comment]
Hi,

I dont' think a new widget would be necessary to solve the issue. But if there is something that would prohibit the use of a negative value, then sure. Otherwise just allowing the byte indicator to display the bits of a value without limiting the value to be positive would be great.

**Comment by klauer** [comment]
What do you expect that the bits of a negative value _should_ be in your application?

I think the ByteIndicator doesn't support (negative) signed values because they don't make much sense from the perspective of displaying a bit mask as a string of on/off LEDs.

For a bit of background - when it comes to representing negative numbers on a computer, it could be through one's/two's complement or even just the most significant bit could represent the sign (see [here](https://en.wikipedia.org/wiki/Signedness)). Additionally, there's a matter of the bit width - if we are to sign extend the negative number to show it in the byte indicator, are we talking 32-bit integers in every case? Most likely not. PyDM (to my recollection) doesn't retain the bit width of integer values from the control system, so does the byte indicator need a bit width setting for negative numbers?

**Comment by nstelter-slac** [comment]
hi,

agree that two's complement for negative numbers doesn't make much sense here, 
seems difficult to interpret compared to unsigned binary and positive numbers in two's representation would be confusing.

not super familiar with all the use cases of this widget, but seems reasonable to drop the sign and display the absolute value of negative numbers. (what i interpreted [jozamudi](https://github.com/jozamudi)'s ask to be, but please clarify if not), especially if added as toggleable option for the widget (off by default) and possibly some visual indication that its displaying negative.

currently negative numbers display nothing in the widget, so think that toggle adds additional functionality without compromising original usage.

**Comment by jjanice** [comment]
I'm trying to recreate EDM functionality. I have an 8-bit indicator with 0 shift and -1 is the same as 255, -2 = 254, .... numBits is set in pydm.

PyDM behaves like edm for numbers > 255: 256=0, 257=1, etc.

Could we use that? Otherwise I think I have to write python to use the fancy multi-state widget. I have some expert screen with 875 (!) byte indicators.

**Comment by nstelter-slac** [comment]
Hello, 

we have been sitting on an unmerged patch that adds negative-number to the display here: https://github.com/slaclab/pydm/pull/1025 , 
but in this patch we just display the negative number as 'abs(negative number)' (ex: -4 displays same as 4).

but also ive modified that patch to work as your described EDM screen, here: https://github.com/slaclab/pydm/pull/1088 (its a minor change from the other patch)

is there use-cases for both options still? we could match EDM by default (2nd option) and then display 'abs(negative value)' as an option to user can select

**Comment by jjanice** [comment]
I don't currently have a use for abs(neg value) but do have a use for EDM
matching.

Also in byte.py line 205/206 (bits = [(value>>i)...) works just like EDM
for negative numbers and numbers greater than 2**numBits - no need for the
value = (2**numBits - abs(value)) if value<0... first.  I suspect EDM has
something similar under the hood or it uses modulus (-1%256=255...)

Thank you for your help with this!

**Comment by nstelter-slac** [comment]
ok good point, ive updated the patch: https://github.com/slaclab/pydm/pull/1088

we can try to get this reviewed early next week, thanks!

**Comment by nstelter-slac** [comment]
closing this out since https://github.com/slaclab/pydm/pull/1088 was merged
